import type { Category, Product } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Dog Supplies',
    slug: 'dog-supplies',
    image: 'https://picsum.photos/400/300',
    description: 'Everything your furry friend needs, from food to toys.',
    dataAiHint: 'happy dog',
  },
  {
    id: '2',
    name: 'Cat Supplies',
    slug: 'cat-supplies',
    image: 'https://picsum.photos/400/300',
    description: 'Treat your feline to the best products available.',
    dataAiHint: 'playful cat',
  },
  {
    id: '3',
    name: 'Bird Supplies',
    slug: 'bird-supplies',
    image: 'https://picsum.photos/400/300',
    description: 'Cages, food, and accessories for your feathered companions.',
    dataAiHint: 'colorful bird',
  },
  {
    id: '4',
    name: 'Fish Supplies',
    slug: 'fish-supplies',
    image: 'https://picsum.photos/400/300',
    description: 'Aquariums, filters, and food for your aquatic pets.',
    dataAiHint: 'goldfish aquarium',
  },
];

export const products: Product[] = [
  // Dog Supplies
  {
    id: 'prod1',
    name: 'Premium Dog Food - Chicken',
    slug: 'premium-dog-food-chicken',
    categoryId: '1',
    images: ['https://picsum.photos/600/400?random=1', 'https://picsum.photos/600/400?random=2', 'https://picsum.photos/600/400?random=3'],
    description: 'Nutritious and delicious premium chicken flavored dog food. Made with real chicken and wholesome grains. Suitable for all breeds.',
    price: 25.99,
    sku: 'DOG-FOOD-001',
    stock: 150,
    rating: 4.5,
    dataAiHint: 'dog food bag',
  },
  {
    id: 'prod2',
    name: 'Durable Chew Toy for Dogs',
    slug: 'durable-chew-toy-dogs',
    categoryId: '1',
    images: ['https://picsum.photos/600/400?random=4', 'https://picsum.photos/600/400?random=5'],
    description: 'A long-lasting chew toy designed for aggressive chewers. Helps clean teeth and gums.',
    price: 12.50,
    sku: 'DOG-TOY-001',
    stock: 200,
    rating: 4.2,
    dataAiHint: 'dog chew toy',
  },
  {
    id: 'prod3',
    name: 'Cozy Dog Bed - Large',
    slug: 'cozy-dog-bed-large',
    categoryId: '1',
    images: ['https://picsum.photos/600/400?random=6'],
    description: 'Soft and comfortable large dog bed. Provides excellent support and promotes restful sleep.',
    price: 45.00,
    sku: 'DOG-BED-001',
    stock: 50,
    rating: 4.8,
    dataAiHint: 'dog bed',
  },

  // Cat Supplies
  {
    id: 'prod4',
    name: 'Gourmet Cat Food - Salmon',
    slug: 'gourmet-cat-food-salmon',
    categoryId: '2',
    images: ['https://picsum.photos/600/400?random=7', 'https://picsum.photos/600/400?random=8'],
    description: 'Delicious salmon flavored gourmet cat food. Rich in Omega-3 and essential nutrients for a healthy coat.',
    price: 18.75,
    sku: 'CAT-FOOD-001',
    stock: 120,
    rating: 4.6,
    dataAiHint: 'cat food can',
  },
  {
    id: 'prod5',
    name: 'Interactive Feather Wand Toy',
    slug: 'interactive-feather-wand-toy',
    categoryId: '2',
    images: ['https://picsum.photos/600/400?random=9'],
    description: 'Engage your cat with this fun and interactive feather wand. Stimulates natural hunting instincts.',
    price: 8.99,
    sku: 'CAT-TOY-001',
    stock: 300,
    rating: 4.3,
    dataAiHint: 'cat feather toy',
  },
  {
    id: 'prod6',
    name: 'Cat Scratching Post with Platform',
    slug: 'cat-scratching-post-platform',
    categoryId: '2',
    images: ['https://picsum.photos/600/400?random=10', 'https://picsum.photos/600/400?random=11'],
    description: 'Sturdy scratching post with a comfortable viewing platform. Helps protect your furniture.',
    price: 32.00,
    sku: 'CAT-SCRATCH-001',
    stock: 70,
    rating: 4.7,
    dataAiHint: 'cat scratching post',
  },

  // Bird Supplies
  {
    id: 'prod7',
    name: 'Premium Bird Seed Mix',
    slug: 'premium-bird-seed-mix',
    categoryId: '3',
    images: ['https://picsum.photos/600/400?random=12'],
    description: 'A balanced mix of seeds, nuts, and fruits for various bird species. High in energy and nutrients.',
    price: 15.20,
    sku: 'BIRD-SEED-001',
    stock: 90,
    rating: 4.4,
    dataAiHint: 'bird seed bag',
  },
  {
    id: 'prod8',
    name: 'Spacious Bird Cage',
    slug: 'spacious-bird-cage',
    categoryId: '3',
    images: ['https://picsum.photos/600/400?random=13', 'https://picsum.photos/600/400?random=14'],
    description: 'A large and secure cage for medium-sized birds, with multiple perches and feeding bowls.',
    price: 75.50,
    sku: 'BIRD-CAGE-001',
    stock: 30,
    rating: 4.1,
    dataAiHint: 'bird cage',
  },

  // Fish Supplies
  {
    id: 'prod9',
    name: 'Aquarium Starter Kit - 10 Gallon',
    slug: 'aquarium-starter-kit-10g',
    categoryId: '4',
    images: ['https://picsum.photos/600/400?random=15'],
    description: 'Complete 10-gallon aquarium kit including filter, heater, and LED lighting. Perfect for beginners.',
    price: 99.99,
    sku: 'FISH-AQUA-001',
    stock: 25,
    rating: 4.0,
    dataAiHint: 'fish tank',
  },
  {
    id: 'prod10',
    name: 'Tropical Fish Flakes',
    slug: 'tropical-fish-flakes',
    categoryId: '4',
    images: ['https://picsum.photos/600/400?random=16'],
    description: 'High-quality fish flakes for tropical fish. Enhances color and vitality.',
    price: 7.50,
    sku: 'FISH-FOOD-001',
    stock: 180,
    rating: 4.3,
    dataAiHint: 'fish food flakes',
  },
   {
    id: 'prod11',
    name: 'Adjustable Pet Leash',
    slug: 'adjustable-pet-leash',
    categoryId: '1', // Dog
    images: ['https://picsum.photos/600/400?random=17', 'https://picsum.photos/600/400?random=18'],
    description: 'Durable and adjustable leash for dogs of all sizes. Features a comfortable grip and reflective stitching for night walks.',
    price: 19.99,
    sku: 'DOG-LEASH-001',
    stock: 100,
    rating: 4.6,
    dataAiHint: 'dog leash',
  },
  {
    id: 'prod12',
    name: 'Soft Cat Collar with Bell',
    slug: 'soft-cat-collar-bell',
    categoryId: '2', // Cat
    images: ['https://picsum.photos/600/400?random=19'],
    description: 'Comfortable and stylish cat collar with a safety release buckle and a small bell.',
    price: 9.50,
    sku: 'CAT-COLLAR-001',
    stock: 150,
    rating: 4.2,
    dataAiHint: 'cat collar',
  }
];
